
version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: uthmanmohamed
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - webapp
    restart: unless-stopped

  backend:
    build: backend
    container_name: emporium-shopping-backend
    image: 1239uth/emporium-shopping-backend:latest
    depends_on:
     - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: uthmanmohamed
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8080:8080"
    networks:
      - webapp

  frontend:
    build: frontend
    container_name: emporium-shopping-frontend
    image: 1239uth/emporium-shopping-frontend:latest
    depends_on:
     - backend
    ports:
      - "3000:8081"
    networks:
      - webapp

networks:
  webapp:
    driver: bridge

volumes:
  postgres: