name: Backend Unit Tests

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: mvn -f backend/pom.xml --batch-mode -DskipTests package

      - name: Unit Tests
        run: mvn -f backend/pom.xml --batch-mode test
